live_config_reload = true

[window]
resize_increments = true
opacity = 0.85
decorations = 'none'

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 130
lines = 42

[font]
normal.family = "Inconsolata Nerd Font"
size = 18

